import { College, CollegeReview, Post, Community, UserProfile } from '@/types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-arun',
    username: 'arun_prakash',
    email: 'arun@campuslenz.org',
    role: 'student',
    fullName: 'Arun Prakash',
    headline: 'MCA Student @ PSG College of Technology | Full-Stack Aspirant',
    bio: '2nd Year Master of Computer Applications student at PSG Tech. Passionate about Next.js, Cloud Architectures, and System Design.',
    collegeId: 'col-psg',
    collegeName: 'PSG College of Technology',
    department: 'Computer Applications',
    course: 'MCA',
    graduationBatch: '2026',
    isVerified: true,
    followersCount: 148,
    followingCount: 92,
    followers: ['user-junith', 'user-karthik', 'user-deepak'],
    following: ['user-junith', 'user-karthik', 'user-meenakshi'],
    createdAt: '2025-08-10T00:00:00Z'
  },
  {
    id: 'user-junith',
    username: 'junith_dev',
    email: 'junith@campuslenz.org',
    role: 'student',
    fullName: 'Junith S',
    headline: 'B.Tech AI & Data Science @ PSG Tech | Competitive Programmer | Hackathon Finalist',
    bio: 'Exploring Deep Learning, LLM Agents & System Optimization. 3x Smart India Hackathon Finalist. Feel free to connect for collab!',
    collegeId: 'col-psg',
    collegeName: 'PSG College of Technology',
    department: 'Artificial Intelligence & Data Science',
    course: 'B.Tech AI & DS',
    graduationBatch: '2026',
    isVerified: true,
    followersCount: 382,
    followingCount: 195,
    followers: ['user-arun', 'user-deepak', 'user-priya'],
    following: ['user-arun', 'user-karthik', 'user-meenakshi'],
    createdAt: '2025-07-01T00:00:00Z'
  },
  {
    id: 'user-karthik',
    username: 'karthik_raja',
    email: 'karthik@microsoft.com',
    role: 'alumni',
    fullName: 'Karthik Raja',
    headline: 'Software Engineer II @ Microsoft | PSG Tech Alum (Batch 2023) | Mentor',
    bio: 'Alumni of PSG Tech CSE. Currently building distributed backend systems at Microsoft. Active mentor for campus placement preparation & DSA.',
    collegeId: 'col-psg',
    collegeName: 'PSG College of Technology',
    department: 'Computer Science & Engineering',
    course: 'B.Tech Computer Science',
    graduationBatch: '2023',
    isVerified: true,
    followersCount: 1240,
    followingCount: 310,
    followers: ['user-arun', 'user-junith', 'user-deepak', 'user-priya'],
    following: ['user-meenakshi', 'user-arun'],
    createdAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'user-meenakshi',
    username: 'dr_meenakshi_staff',
    email: 'meenakshi@psgtech.edu',
    role: 'staff',
    fullName: 'Dr. Meenakshi Sundaram',
    headline: 'Professor & Head of Computer Science @ PSG College of Technology | IEEE Senior Member',
    bio: 'Academic researcher in Distributed Computing and Machine Learning. 18+ years of teaching excellence and mentoring engineering innovators.',
    collegeId: 'col-psg',
    collegeName: 'PSG College of Technology',
    department: 'Computer Science & Engineering',
    course: 'Faculty / Staff',
    graduationBatch: 'Faculty',
    isVerified: true,
    followersCount: 890,
    followingCount: 120,
    followers: ['user-arun', 'user-junith', 'user-karthik'],
    following: ['user-karthik'],
    createdAt: '2023-06-20T00:00:00Z'
  },
  {
    id: 'user-deepak',
    username: 'deepak_v',
    email: 'deepak@annauniv.edu',
    role: 'student',
    fullName: 'Deepak V',
    headline: 'B.E CSE Student @ CEG Anna University | Open Source Contributor',
    bio: 'Student at College of Engineering, Guindy (CEG). Exploring Linux kernel programming, Rust, and systems engineering.',
    collegeId: 'col-ceg',
    collegeName: 'College of Engineering, Guindy (CEG)',
    department: 'Computer Science',
    course: 'B.E CSE',
    graduationBatch: '2025',
    isVerified: false,
    followersCount: 215,
    followingCount: 140,
    followers: ['user-arun', 'user-junith'],
    following: ['user-arun', 'user-karthik'],
    createdAt: '2025-02-10T00:00:00Z'
  },
  {
    id: 'user-priya',
    username: 'priya_dharshini',
    email: 'priya@snsct.org',
    role: 'student',
    fullName: 'Priya Dharshini',
    headline: 'MCA Student @ SNS College of Technology | UI/UX Designer & Web Developer',
    bio: 'Building user-centric web applications and experimenting with Design Thinking models. President of Campus Web Developers Club.',
    collegeId: 'col-sns',
    collegeName: 'SNS College of Technology',
    department: 'Computer Applications',
    course: 'MCA',
    graduationBatch: '2025',
    isVerified: true,
    followersCount: 310,
    followingCount: 180,
    followers: ['user-arun', 'user-junith'],
    following: ['user-arun', 'user-junith', 'user-karthik'],
    createdAt: '2025-03-01T00:00:00Z'
  }
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-junith-1',
    authorId: 'user-junith',
    authorUsername: 'junith_dev',
    authorName: 'Junith S',
    authorRole: 'student',
    authorHeadline: 'B.Tech AI & Data Science @ PSG Tech | Competitive Programmer',
    isVerifiedAuthor: true,
    isAnonymous: false,
    collegeId: 'col-psg',
    collegeName: 'PSG College of Technology',
    content: 'Thrilled to share that our campus AI research team just published our paper on "Optimizing Inference on Resource-Constrained Edge Devices"! 🚀\n\nA huge thank you to Dr. Meenakshi and the PSG Tech CSE lab facilities for the continuous compute support. For 2nd and 3rd year juniors looking to get into research, the robotics & AI lab applications open next week. Don\'t miss it!',
    topic: 'Research & Achievements',
    likes: ['user-arun', 'user-karthik', 'user-meenakshi'],
    likesCount: 42,
    commentsCount: 3,
    sharesCount: 11,
    createdAt: '2026-09-26T16:30:00Z',
    moderationStatus: 'normal',
    comments: [
      {
        id: 'c-1',
        postId: 'post-junith-1',
        authorId: 'user-karthik',
        authorUsername: 'karthik_raja',
        authorName: 'Karthik Raja',
        authorRole: 'alumni',
        authorHeadline: 'Software Engineer II @ Microsoft | PSG Tech Alum',
        isVerifiedAuthor: true,
        content: 'Brilliant work Junith! Edge optimization is extremely relevant in industry right now. Reach out if you want to test scaling metrics on Azure infrastructure.',
        createdAt: '2026-09-26T17:00:00Z',
        likesCount: 8
      },
      {
        id: 'c-2',
        postId: 'post-junith-1',
        authorId: 'user-arun',
        authorUsername: 'arun_prakash',
        authorName: 'Arun Prakash',
        authorRole: 'student',
        authorHeadline: 'MCA Student @ PSG Tech',
        isVerifiedAuthor: true,
        content: 'Congratulations Junith! Would love to learn more about the dataset used during the lab session.',
        createdAt: '2026-09-26T17:25:00Z',
        likesCount: 3
      },
      {
        id: 'c-3',
        postId: 'post-junith-1',
        authorId: 'user-meenakshi',
        authorUsername: 'dr_meenakshi_staff',
        authorName: 'Dr. Meenakshi Sundaram',
        authorRole: 'staff',
        authorHeadline: 'Professor & Head of CSE @ PSG Tech',
        isVerifiedAuthor: true,
        content: 'Very proud of the dedication shown by the team. Keep up the high academic standards!',
        createdAt: '2026-09-26T18:10:00Z',
        likesCount: 12
      }
    ]
  },
  {
    id: 'post-karthik-1',
    authorId: 'user-karthik',
    authorUsername: 'karthik_raja',
    authorName: 'Karthik Raja',
    authorRole: 'alumni',
    authorHeadline: 'Software Engineer II @ Microsoft | PSG Tech Alum',
    isVerifiedAuthor: true,
    isAnonymous: false,
    collegeId: 'col-psg',
    collegeName: 'PSG College of Technology',
    content: 'Tips for upcoming tier-1 product campus drives:\n\n1. Stop grinding LeetCode blindly without understanding patterns (Sliding Window, Two Pointers, Monotonic Stack).\n2. Write clean modular code with descriptive variable names in your interview rounds.\n3. Be prepared to explain trade-offs between Space and Time complexity clearly.\n\nOpen for mock interviews and resume reviews this Saturday. Drop a comment or message request with your current year!',
    topic: 'Alumni Mentorship',
    likes: ['user-arun', 'user-junith', 'user-deepak', 'user-priya'],
    likesCount: 89,
    commentsCount: 2,
    sharesCount: 24,
    createdAt: '2026-09-25T11:05:00Z',
    moderationStatus: 'normal',
    comments: [
      {
        id: 'c-4',
        postId: 'post-karthik-1',
        authorId: 'user-arun',
        authorUsername: 'arun_prakash',
        authorName: 'Arun Prakash',
        authorRole: 'student',
        authorHeadline: 'MCA Student @ PSG Tech',
        isVerifiedAuthor: true,
        content: 'Count me in Karthik bhaiya! Sending my resume via message request.',
        createdAt: '2026-09-25T12:00:00Z',
        likesCount: 4
      },
      {
        id: 'c-5',
        postId: 'post-karthik-1',
        authorId: 'user-deepak',
        authorUsername: 'deepak_v',
        authorName: 'Deepak V',
        authorRole: 'student',
        authorHeadline: 'B.E CSE @ CEG Anna University',
        isVerifiedAuthor: false,
        content: 'Super helpful advice. Does Microsoft also focus on Low-Level Design (LLD) for fresher campus hiring?',
        createdAt: '2026-09-25T13:40:00Z',
        likesCount: 2
      }
    ]
  },
  {
    id: 'post-deepak-1',
    authorId: 'user-deepak',
    authorUsername: 'deepak_v',
    authorName: 'Deepak V',
    authorRole: 'student',
    authorHeadline: 'B.E CSE Student @ CEG Anna University',
    isVerifiedAuthor: false,
    isAnonymous: false,
    collegeId: 'col-ceg',
    collegeName: 'College of Engineering, Guindy (CEG)',
    content: 'CEG coding club is hosting a 24-hour inter-college hackathon on Distributed Systems & Web3 next month. Registrations are open to all colleges across Tamil Nadu. Teams of 2 to 4.',
    topic: 'Hackathons & Events',
    likes: ['user-arun', 'user-junith'],
    likesCount: 28,
    commentsCount: 1,
    sharesCount: 9,
    createdAt: '2026-09-24T18:20:00Z',
    moderationStatus: 'normal',
    comments: [
      {
        id: 'c-6',
        postId: 'post-deepak-1',
        authorId: 'user-junith',
        authorUsername: 'junith_dev',
        authorName: 'Junith S',
        authorRole: 'student',
        authorHeadline: 'B.Tech AI & DS @ PSG Tech',
        isVerifiedAuthor: true,
        content: 'PSG Tech AI club is registering 2 teams! Looking forward to meeting everyone in Chennai.',
        createdAt: '2026-09-24T19:10:00Z',
        likesCount: 5
      }
    ]
  },
  {
    id: 'post-anon-1',
    authorId: 'user-anon-9',
    authorUsername: 'anonymous_student',
    authorName: 'Anonymous Student',
    authorRole: 'student',
    authorHeadline: 'Current Student • Confidential Review',
    isVerifiedAuthor: false,
    isAnonymous: true,
    collegeId: 'col-sns',
    collegeName: 'SNS College of Technology',
    content: 'Honest update on hostel facilities: While the design thinking labs and academic classrooms are top notch, the Block B hostel Wi-Fi latency needs serious improvement during contest hours. Can the student council take this up in next month\'s faculty meeting?',
    topic: 'Hostel & Campus Life',
    likes: ['user-priya'],
    likesCount: 19,
    commentsCount: 1,
    sharesCount: 2,
    createdAt: '2026-09-26T14:10:00Z',
    moderationStatus: 'normal',
    comments: [
      {
        id: 'c-7',
        postId: 'post-anon-1',
        authorId: 'user-priya',
        authorUsername: 'priya_dharshini',
        authorName: 'Priya Dharshini',
        authorRole: 'student',
        authorHeadline: 'MCA Student @ SNS CT',
        isVerifiedAuthor: true,
        content: 'Already scheduled for discussion in the IT committee meeting this Tuesday. New 5GHz APs are planned for installation.',
        createdAt: '2026-09-26T15:00:00Z',
        likesCount: 6
      }
    ]
  }
];

export const INITIAL_COLLEGES: College[] = [
  {
    id: 'col-psg',
    slug: 'psg-college-of-technology',
    name: 'PSG College of Technology',
    location: 'Coimbatore',
    state: 'Tamil Nadu',
    collegeType: 'Autonomous',
    establishedYear: 1951,
    contactEmail: 'contact@psgtech.edu',
    contactPhone: '+91 422 2572177',
    websiteUrl: 'https://www.psgtech.edu',
    courses: ['B.Tech Computer Science', 'B.Tech AI & Data Science', 'MCA', 'M.Tech AI'],
    departments: ['Computer Science', 'Artificial Intelligence', 'Mechanical', 'Applied Math'],
    feesMin: 65000,
    feesMax: 120000,
    feesDescription: 'Government aided and self-financing annual fee brackets.',
    placementStats: {
      highestPackage: '38 LPA',
      averagePackage: '8.5 LPA',
      placementRate: '94%',
      topRecruiters: ['Microsoft', 'Amazon', 'Cisco', 'Qualcomm', 'TCS']
    },
    facilities: ['Hostel (Separate Boys/Girls)', 'Central Library', 'Advanced Robotics Lab', 'Sports Complex', 'High-Speed Wi-Fi'],
    officialOverview: 'An autonomous, government-aided institution affiliated with Anna University, committed to technical excellence and industry-driven research.',
    ratingAverage: 4.6,
    reviewCount: 28
  },
  {
    id: 'col-ceg',
    slug: 'college-of-engineering-guindy',
    name: 'College of Engineering, Guindy (CEG Anna University)',
    location: 'Chennai',
    state: 'Tamil Nadu',
    collegeType: 'Government',
    establishedYear: 1794,
    contactEmail: 'deanceg@annauniv.edu',
    contactPhone: '+91 44 2235 7004',
    websiteUrl: 'https://ceg.annauniv.edu',
    courses: ['B.E Computer Science', 'B.E Mechanical', 'B.Tech IT', 'MCA'],
    departments: ['Computer Science and Engineering', 'Information Technology', 'Mechanical Engineering'],
    feesMin: 35000,
    feesMax: 70000,
    feesDescription: 'Affordable government fee structure subsidized by the state.',
    placementStats: {
      highestPackage: '42 LPA',
      averagePackage: '9.2 LPA',
      placementRate: '92%',
      topRecruiters: ['Google', 'Adobe', 'Samsung', 'DE Shaw', 'Infosys']
    },
    facilities: ['Heritage Campus', 'Extensive Technical Library', 'Hostel Facilities', 'Innovation Hub', 'Auditorium'],
    officialOverview: 'One of the oldest technical institutions in Asia, offering premier academic and research programs in core engineering disciplines.',
    ratingAverage: 4.7,
    reviewCount: 35
  },
  {
    id: 'col-sns',
    slug: 'sns-college-of-technology',
    name: 'SNS College of Technology',
    location: 'Coimbatore',
    state: 'Tamil Nadu',
    collegeType: 'Autonomous',
    establishedYear: 2002,
    contactEmail: 'office@snsct.org',
    contactPhone: '+91 422 2666264',
    websiteUrl: 'https://snsct.org',
    courses: ['B.Tech AI & Data Science', 'B.E CSE', 'MCA', 'MBA'],
    departments: ['Computer Science', 'Design Thinking Hub', 'Management Studies'],
    feesMin: 85000,
    feesMax: 150000,
    feesDescription: 'Autonomous annual academic fee including design lab amenities.',
    placementStats: {
      highestPackage: '18 LPA',
      averagePackage: '5.2 LPA',
      placementRate: '88%',
      topRecruiters: ['Cognizant', 'Wipro', 'Accenture', 'Zoho', 'Hexaware']
    },
    facilities: ['Design Thinking Spine', 'Modern Hostels', 'IoT Labs', 'Cafeteria', 'Digital Studio'],
    officialOverview: 'First institution in India to implement Design Thinking framework across all engineering curricula.',
    ratingAverage: 4.1,
    reviewCount: 16
  }
];

export const INITIAL_REVIEWS: CollegeReview[] = [
  {
    id: 'rev-1',
    collegeId: 'col-psg',
    userId: 'user-karthik',
    reviewerType: 'alumni',
    authorName: 'Karthik Raja',
    authorUsername: 'karthik_raja',
    isAnonymous: false,
    overallRating: 4.8,
    dimensions: {
      academics: 5,
      faculty: 4,
      placements: 5,
      infrastructure: 4,
      hostel: 4,
      campusLife: 4,
      valueForMoney: 5,
      studentExperience: 5
    },
    title: 'Superb placements and strong industry connections',
    experience: 'PSG Tech gave me rigorous foundation in Computer Science. The coding culture and hackathons were top tier. Placements were seamless for tech branches.',
    pros: ['Top recruiters visit campus', 'Practical lab culture', 'Very supportive alumni network'],
    cons: ['Strict attendance rules', 'Heavy exam schedule'],
    advice: 'Start competitive programming from 2nd year and participate in club activities.',
    recommendation: true,
    course: 'B.Tech Computer Science',
    department: 'Computer Science',
    batch: '2023',
    createdAt: '2026-02-14T10:30:00Z',
    institutionReply: {
      officialName: 'Dean of Student Affairs (PSG Tech)',
      repliedAt: '2026-02-16T12:00:00Z',
      text: 'Thank you for your valuable feedback Karthik. We are continuously enhancing our curriculum with newer AI-focused industry electives.'
    }
  },
  {
    id: 'rev-2',
    collegeId: 'col-psg',
    userId: 'user-arun',
    reviewerType: 'student',
    authorName: 'Arun Prakash',
    authorUsername: 'arun_prakash',
    isAnonymous: false,
    overallRating: 4.5,
    dimensions: {
      academics: 5,
      faculty: 4,
      placements: 5,
      infrastructure: 4,
      hostel: 3,
      campusLife: 4,
      valueForMoney: 5,
      studentExperience: 4
    },
    title: 'Top-tier curriculum and great coding culture',
    experience: 'The MCA program at PSG Tech is on par with B.Tech CSE curricula. High exposure to practical software engineering and active student developer circles.',
    pros: ['Very strong lab curriculum', 'Helpful seniors & alumni network'],
    cons: ['Hostel mess food can be improved', 'Strict attendance criteria'],
    advice: 'Keep a clean GitHub portfolio and solve LeetCode regularly.',
    recommendation: true,
    course: 'MCA',
    department: 'Applied Sciences & CA',
    batch: '2026',
    createdAt: '2026-03-01T09:15:00Z'
  }
];

export const INITIAL_COMMUNITIES: Community[] = [
  {
    id: 'comm-1',
    name: 'PSG Tech - Alumni & Student Mentorship Circle',
    description: 'Direct knowledge sharing, resume tips, and job referrals between PSG alumni and current students.',
    collegeId: 'col-psg',
    collegeName: 'PSG College of Technology',
    creatorId: 'user-karthik',
    creatorRole: 'alumni',
    isPrivate: false,
    membersCount: 142,
    category: 'mentoring',
    createdAt: '2026-01-10T00:00:00Z'
  },
  {
    id: 'comm-2',
    name: 'SNS Alumni — MCA Network',
    description: 'Official alumni gathering space for MCA graduates from SNS College of Technology. Career opportunities and meetup planning.',
    collegeId: 'col-sns',
    collegeName: 'SNS College of Technology',
    creatorId: 'user-priya',
    creatorRole: 'student',
    isPrivate: false,
    membersCount: 89,
    category: 'alumni',
    createdAt: '2026-02-05T00:00:00Z'
  },
  {
    id: 'comm-3',
    name: 'Tamil Nadu Engineering Aspirants',
    description: 'Cross-college discussion for admissions, cutoffs, counseling, hostel comparisons, and career roadmap.',
    creatorId: 'user-deepak',
    creatorRole: 'student',
    isPrivate: false,
    membersCount: 310,
    category: 'general',
    createdAt: '2025-11-20T00:00:00Z'
  }
];
